Account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_done

from . import views

app_name = 'Account'

urlpatterns = [

    # url(r'^$', views.home, name='home'),
    url(r'^account_manage/$', views.account_manage, name='account_manage'),
    url(r'^profile/$', views.update_profile, name='profile'),
    url(r'^comments/$', views.comments, name='comments'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^ordersHistory/$', views.ordersHistory, name='ordersHistory'),
    url(r'^ordersdetail/(?P<order_id>\d+)/$',
        views.orderdetail, name='orderdetail'),
    url(r'^register/$', views.register, name='register'),

    # login logout
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),

    # change password
    url(r'^password-change/$', password_change, name='password_change'),
    url(r'^password-change/done/$', password_change_done,
        name='password_change_done'),

    # reset password
    # restore password urls
    url(r'^password_reset/$',
        password_reset, {
            'post_reset_redirect': '/Account/password_reset/done/'
        },
        name='password_reset'),
    url(r'^password_reset/done/$',
        password_reset_done,
        name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        password_reset_confirm, {
            'post_reset_redirect': '/Account/reset/done/'
        },
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        password_reset_complete,
        name='password_reset_complete'),
]

IB/urls.py
from django.conf.urls import url

from . import views

app_name = 'IB'

urlpatterns = [
    url(r'^$', views.home,
        name='home'),
    url(r'^booklist/$', views.book_list, name='book_list'),
    url(r'^booklist/(?P<category_slug>[-\w]+)/$', views.book_list,
        name='book_list_by_category'),
    url(r'^booklistFR/$', views.book_list_FR, name='book_list_FR'),
    url(r'^booklistFR/(?P<category_slug>[-\w]+)/$', views.book_list_FR,
        name='book_list_by_category_FR'),
    url(r'^book_list/(?P<book_id>\d+)/(?P<slug>[-\w]+)/$',
        views.book_detail, name='book_detail'),

]

InternetBookstore/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('IB.urls', namespace='IB')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^Account/', include('Account.urls', namespace='Account')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^comment/', include('comment.urls', namespace='comment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

comment/urls.py
from django.conf.urls import url

from . import views

app_name = 'comment'

urlpatterns = [
    url(r'^(?P<book_id>\d+)/createComment/$', views.createComment,
        name='createComment'),
]

IB/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50,
                            db_index=True)
    slug = models.SlugField(max_length=50,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('IB:book_list_by_category',
                       args=[self.slug])

    def get_absolute_url_FR(self):
        return reverse('IB:book_list_by_category_FR',
                       args=[self.slug])


class Book(models.Model):
    isbn = models.CharField(max_length=30, unique=True)
    bookname = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True)
    author = models.CharField(max_length=30)
    publisher = models.CharField(max_length=30)
    publish_date = models.DateField()
    description = models.TextField(null=True)
    photo = models.URLField(null=True)
    state = models.BooleanField(default=True)
    price = models.IntegerField()
    stock = models.IntegerField()
    Foreign = 'FR'
    Chinese = 'CH'
    LANGUAGE_CHOICES = (
        (Foreign, 'Foreign'),
        (Chinese, 'Chinese'),
    )
    language = models.CharField(max_length=10,
                                choices=LANGUAGE_CHOICES,
                                default=Chinese)
    category = models.ForeignKey(Category,
                                 related_name='books',
                                 null=True,
                                 on_delete=models.SET_NULL)

    class Meta:
        ordering = ('bookname',)
        index_together = [['id', 'slug']]

    def __str__(self):
        return self.bookname

    def get_absolute_url(self):
        return reverse('IB:book_detail',
                       args=[self.id, self.slug])


# class Comment(models.Model):
#     book_id = models.ForeignKey(Book, null=True, on_delete=models.CASCADE)
#     account_id = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
#     description = models.TextField()
#     date_time = models.DateTimeField()

IB/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import *
from cart.forms import CartAddBookForm
from comment.models import Comment
# Create your views here.


def home(request):
    books = Book.objects.all().order_by('?')[:12]
    return render(request, 'home.html', {'books': books})


def book_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    books = Book.objects.filter(state=True, language='CH')
    query = request.GET.get("q")
    if query:
        books = Book.objects.filter(
            Q(bookname__icontains=query) |
            Q(author__icontains=query) |
            Q(publisher__icontains=query) |
            Q(isbn__icontains=query) |
            Q(category__name__icontains=query)).distinct()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = books.filter(category=category)
    paginator = Paginator(books, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request,
                  'Books.html',
                  {'category': category,
                   'categories': categories,
                   'books': contacts})


def book_list_FR(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    books = Book.objects.filter(state=True, language='FR')
    query = request.GET.get("q")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = books.filter(category=category)
    paginator = Paginator(books, 9)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    return render(request,
                  'FRBooks.html',
                  {'category': category,
                   'categories': categories,
                   'books': contacts})


def book_detail(request, book_id, slug):
    book = get_object_or_404(Book, id=book_id,
                             slug=slug, state=True)
    cart_book_form = CartAddBookForm()
    try:
        comments = Comment.objects.filter(book=book_id)
    except Comment.DoesNotExist:
        comments = None
    return render(request,
                  'bookdetail.html',
                  {'book': book,
                   'cart_book_form': cart_book_form,
                   'comments': comments
                   })

IB/templates/Books.html
{% extends "./base.html "%}
{% load staticfiles %}


{% block title %}
    {% if category %}{{ category.title }}{% else %}Books{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h3>Categories</h3>
            <div class="list-group">
                {% for c in categories %}
                    <div {% if category.slug == c.slug %}class="active"{% endif %}>
                        <a class="list-group-item list-group-item-action"
                        href="{{c.get_absolute_url}}" style="text-decoration: none;">{{c.name}}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9 book">
            <h2>{% if category %}{{ category.name }}{% else %}Books{% endif %}</h2>
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a href="{{ book.get_absolute_url }}" style="text-decoration: none;">
                            <img src="{% if book.photo %}{{ book.photo}}
                            {% else %}{% static "IB/no_img.png" %} {% endif %}">
                        </a>
                        <a href="{{ book.get_absolute_url }}" style="text-decoration: none;">{{book.bookname }}</a><br>
                        ${{ book.price }}
                    </div>
                </div>
                {% endfor %}

                {% if books.paginator.num_pages != 1%}
                <div class="row mx-auto">
                <ul class="pagination pagination-sm">
                    {% if books.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link">&laquo; first</a>
                    </li>
                    <li class="page-item">
                            <a href="?page={{ books.previous_page_number }}" class="page-link">Previous</a>
                            {% endif %}
                    </li>
                    <li class="page-item disabled">

                            <a href="?page={{ books.current_page_number }}" class="page-link">
                            Page {{ books.number }} of {{ books.paginator.num_pages }}
                        </a>
                    </li>
                            {% if books.has_next %}
                        <li class="page-item">
                            <a href="?page={{ books.next_page_number }}" class="page-link">Next</a>
                        </li>
                        <li class="page-item">
                        <a href="?page={{ books.paginator.num_pages }}" class="page-link">last &raquo;</a>
                    </li>
                    {% endif %}
                </ul>
                </div>
                {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock%}

IB/templates/ChineseBooks.html
{% extends "./base.html "%}
{% load staticfiles %}


{% block title %}
    {% if category %}{{ category.title }}{% else %}Books{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h3>Categories</h3>
            <div class="list-group">
                <div {% if not category %}class="active"{% endif %}>
                    <a class="list-group-item list-group-item-action"
                    href="{% url "IB:book_list"%}" >ALL</a>
                </div>
                {% for c in categories %}
                    <div {% if category.slug == c.slug %}class="active"{% endif %}>
                        <a class="list-group-item list-group-item-action"
                        href="{{c.get_absolute_url}}">{{c.name}}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9 book">
            <h2>{% if category %}{{ category.name }}{% else %}Books{% endif %}</h2>
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a href="{{ book.get_absolute_url }}">
                            <img src="{% if book.photo %}{{ book.photo}}
                            {% else %}{% static "IB/no_img.png" %} {% endif %}">
                        </a>
                        <a href="{{ book.get_absolute_url }}">{{book.bookname }}</a><br>
                        ${{ book.price }}
                    </div>
                </div>
                {% endfor %}
        </div>
    </div>
</div>
</div>
{% endblock%}

IB/templates/FRBooks.html
{% extends "./base.html "%}
{% load staticfiles %}


{% block title %}
    {% if category %}{{ category.title }}{% else %}Books{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h3>Categories</h3>
            <div class="list-group">
                {% for c in categories %}
                    <div {% if category.slug == c.slug %}class="active"{% endif %}>
                        <a class="list-group-item list-group-item-action"
                        href="{{c.get_absolute_url_FR}}" style="text-decoration: none;">{{c.name}}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9 book">
            <h2>{% if category %}{{ category.name }}{% else %}Books{% endif %}</h2>
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a href="{{ book.get_absolute_url }}">
                            <img src="{% if book.photo %}{{ book.photo}}
                            {% else %}{% static "IB/no_img.png" %} {% endif %}">
                        </a>
                        <a href="{{ book.get_absolute_url }}" style="text-decoration: none;">{{book.bookname }}</a><br>
                        ${{ book.price }}
                    </div>
                </div>
                {% endfor %}
                {% if books.paginator.num_pages != 1%}
                <div class="row mx-auto">
                <ul class="pagination pagination-sm">
                    {% if books.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link">&laquo; first</a>
                    </li>
                    <li class="page-item">
                            <a href="?page={{ books.previous_page_number }}" class="page-link">Previous</a>
                            {% endif %}
                    </li>
                    <li class="page-item disabled">

                            <a href="?page={{ books.current_page_number }}" class="page-link">
                            Page {{ books.number }} of {{ books.paginator.num_pages }}
                        </a>
                    </li>
                            {% if books.has_next %}
                        <li class="page-item">
                            <a href="?page={{ books.next_page_number }}" class="page-link">Next</a>
                        </li>
                        <li class="page-item">
                        <a href="?page={{ books.paginator.num_pages }}" class="page-link">last &raquo;</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
        {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock%}

IB/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
  <title>{% block title %}{% endblock %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

  <link rel="stylesheet" type="text/css" href="{% static "css/book.css" %}">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

</head>

<body>
    {% include 'messages.html' %}
  <ul class="nav nav-tabs justify-content-end  sticky-top">
  <li class="nav-item">
  {% if request.user.is_authenticated %}
      <a class="nav-link" href="{% url "Account:account_manage"%}"> Hello {{ request.user.first_name }}</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url "Account:logout" %}">Logout</a>
  {% else %}
      <a class="nav-link" href="{% url "Account:login" %}">Login</a>
  {% endif %}
  </li>
    <li class="nav-item">
      <form action="{% url "IB:book_list" %}" class="form-inline" method="GET">
          <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" value='{{ request.GET.q }}'>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <li class="nav-item">
        <a class="nav-link" href="{% url "cart:cart_detail" %}">購物車</a>
      </li>
    </li>

  </ul>
  <div class="container">
    <div class="jumbotron text-Info">
      <img class="float-right" src="https://www.jiumodiary.com/images/front/eleps.png" style="width:29%;height:25%">
      <div>
          <a href="/" style="text-decoration: none;"><h1>InternetBookstore</h1></a>
          <p>Welcome to InternetBookstore!!</p>
      </div>
    </div>
    <ul class="nav nav-tabs justify-content-center nav-justified">
      <li class="nav-item">
        <a class="nav-link" href="/">首頁</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "IB:book_list" %}">中文書</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "IB:book_list_FR" %}">外文書</a>
      </li>
    </ul>
    {% block content %}
    {% endblock %}
</body>
<footer style="text-align:center">
  <p>Posted by: Tsai</p>
  <p>Contact information: <a href="mailto:wto2005716@yahoo.com.tw" style="text-decoration:none">
  wto2005716@yahoo.com.tw</a>.</p>
</footer>
</html>

IB/templates/bookdetail.html
{% extends "./base.html "%}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}
    {% if category %}{{ category.title }}{% else %}Books{% endif %}
{% endblock %}

{% block content %}

<div class="border_image">
  <div class="row">
    <div class="col-md-5 mx-auto">
        <div class="thumbnail">
            <p></p>
            <img src="{% if book.photo %}{{ book.photo }}
                      {% else %}{% static "IB/no_image.png" %}{% endif %}"
                 class="img-responsive">
                 <p></p>
             </div>
             </div>
             <div class="col-md-6">
                    <div class="col-md-10 col-xs-6">
                        <p> </p>
                        <h3>{{ book.bookname }}</h3>
                        <p> </p>
                        <p>作者 / {{book.author}}</p>
                        <p>出版社 / {{book.publisher}}</p>
                        <p>出版日期 / {{book.publish_date}}</p>
                        <p>語言 / {{book.language}}</p>
                        <p>定價 / {{book.price}}</p>
                        <p>存貨 / <span class="badge badge-success">In Stock</span></p>
                        <p>書籍種類 / <a href="{{ book.category.get_absolute_url }}" style="text-decoration: none;">
                            {{ book.category }}</a></p>
                        <p> </p>

                        <form action="{% url "cart:cart_add" book.id %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_form cart_book_form %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success btn-product">
                                            <span class="glyphicon glyphicon-shopping-cart"></span> Add to cart
                                        </button>
                                    {% endbuttons %}
                        </form>
                    </div>
                </div>
              </div>
            </div>

    <div class="row">
            <div class="card col-md-6 scroll">
              <div class="card-body">
                <h4 class ="card-title">內容簡介</h4>
                <p class="card-text">{{ book.description }}</p>
              </div>
              <p></p>
            </div>

    <div class="card col-md-6 scroll">
        <button type="button" class="btn btn-light" >
                <a href="{% url "comment:createComment" book.id %}" style="text-decoration: none;">Comment</a>
        </button>
        {% for comment in comments %}
        <div class="card">
            <div class="card-body">
             <h5 class="card-title">Writer: {{comment.user}}</h5>
            <p class="card-text">{{comment.content}}</p>
            <p class="card-text float-right"> At:{{comment.timestamp}}</p>
        </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

IB/templates/carousel.html
<div id="activity" class="carousel slide" data-ride="carousel" style=" width:80%;height:80%;margin: 0 auto;">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#activity" data-slide-to="0" class="active"></li>
    <li data-target="#activity" data-slide-to="1"></li>
    <li data-target="#activity" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/static/IB/test1.jpg" alt="test1" style="width:100%;height=100%;">
    </div>
    <div class="carousel-item">
      <img src="/static/IB/test2.jpg" alt="test2" style="width:100%;height=100%;">
    </div>
    <div class="carousel-item">
      <img src="/static/IB/test3.jpg" alt="test3" style="width:100%;height=100%;">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#activity" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#activity" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

IB/templates/home.html
{% extends "./base.html" %}
{% load staticfiles %}

{% block content %}
    <!-- carousel -->
    {% include 'carousel.html' %}
    <div>
      <h5>精選書籍</h5>
    </div>

    <div class="row">
        {% for book in books %}
        <div class="col-md-3 book">
            <div class="thumbnail">
                <a href="{{ book.get_absolute_url }}" style="text-decoration: none;">
                    <img src="{% if book.photo %}{{ book.photo}}
                    {% else %}{% static "IB/no_img.png" %} {% endif %}">
                </a>
                <div>
                <a href="{{ book.get_absolute_url }}" style="text-decoration: none;">{{book.bookname }}</a><br>
            </div>
                ${{ book.price }}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

IB/templates/messages.html
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}