IB/urls.py
from django.conf.urls import url

from . import views

app_name = 'IB'

urlpatterns = [
    url(r'^$', views.home,
        name='home'),
    url(r'^booklist/$', views.book_list, name='book_list'),
    url(r'^booklist/(?P<category_slug>[-\w]+)/$', views.book_list,
        name='book_list_by_category'),
    url(r'^booklistFR/$', views.book_list_FR, name='book_list_FR'),
    url(r'^booklistFR/(?P<category_slug>[-\w]+)/$', views.book_list_FR,
        name='book_list_by_category_FR'),
    url(r'^book_list/(?P<book_id>\d+)/(?P<slug>[-\w]+)/$',
        views.book_detail, name='book_detail'),

]

InternetBookstore/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('IB.urls', namespace='IB')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^Account/', include('Account.urls', namespace='Account')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^comment/', include('comment.urls', namespace='comment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = "orders"

urlpatterns = [
    url(r'^createOrder/$',
        views.order_create,
        name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=BOOK_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages

from IB.models import Book
from .cart import Cart
from .forms import CartAddBookForm
from discount.models import Discount

# Create your views here.


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)

    try:
        policy = Discount.objects.get(category=book.category)
        discount = policy.discount
    except Discount.DoesNotExist:
        discount = 1

    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book,
                 discount=discount,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
        messages.success(request,
                         'Successfully add to cart!')
    else:
        messages.error(request, 'The book can\'t be add to cart!')
    return redirect('IB:book_list')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    # 使用 for in 的時候，他會開始迭代，並且呼叫 `__iter__`
    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    return render(request, 'cart_detail.html', {'cart': cart})

cart/templates/cart_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>購物車</h1>
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1 mx-auto">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Book</th>
                        <th>Quantity</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Discount</th>
                        <th class="text-center">Total</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with book=item.book %}
                    <tr>
                        <td class="col-sm-8 col-md-6">
                            <div class="media">
                                <a class="thumbnail pull-left" href="{{ book.get_absolute_url }}" >
                                    <img class="media-object"
                                         src="{% if book.photo %}{{ book.photo }}
                                              {% else %}{% static "IB/no_image.png" %}{% endif %}"
                                         style="width: 72px; height: 72px;">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a
                                            href="{{ book.get_absolute_url }}" style="text-decoration:none">{{ book.bookname }}</a></h4>
                                    <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                                </div>
                            </div>
                        </td>
                        <td class="col-sm-1 col-md-1" style="text-align: center">
                                <form action="{% url "cart:cart_add" book.id %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_field item.update_quantity_form.quantity show_label=False %}
                                    {% bootstrap_field item.update_quantity_form.update %}
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success btn-product">
                                            Check
                                        </button>
                                    {% endbuttons %}
                                </form>
                        </td>
                        <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.price }}</strong></td>
                        <td class="col-sm-1 col-md-1 text-center"><strong>${{item.discount}}</strong></td>
                        <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.total_price }}</strong></td>

                        <td class="col-sm-1 col-md-1">
                            <a href="{% url "cart:cart_remove" book.id %}" class="btn btn-danger">
                                <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Remove
                            </a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h5>Ship Cost</h5></td>
                    <td class="text-right"><h5><strong>${{ cart.get_shipment_cost }}</strong></h3></td>
            </tr>
            <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h5>Total</h5></td>
                    <td class="text-right"><h5><strong>${{ cart.get_total_cost }}</strong></h3></td>
            </tr>
            <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td> </td>
                    <td>

                        <button  type="button" class="btn btn-light">
                        <a href="{% url "IB:book_list"%}" class="btn btn-default">
                            Continue Shopping
                        </a>
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-light">
                        <a href="{% url "orders:order_create" %}" class="btn btn-default">Checkout
                        </a>
                    </button>


                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

                    </tr>
            </table>
        </div>
    </div>
{% endblock %}